<template>
  <VueLoading
    :active="loadings.fullLoading"
    :background-color="'#000'"
    :opacity="loadings.opacity"
    :blur="'5px'"
  >
    <!-- 首頁 loading 才顯示漸層效果 -->
    <div
      v-if="loadings.opacity === 1"
      class="fixed top-0 left-0 w-full h-screen"
      style="
        background: linear-gradient(
          142.88deg,
          rgba(255, 255, 255, 0.16) 8.09%,
          rgba(255, 255, 255, 0.064) 27.24%,
          rgba(255, 255, 255, 0.064) 34.42%,
          rgba(255, 255, 255, 0.1088) 48.78%,
          rgba(255, 255, 255, 0) 100%
        );
      "
    ></div>
    <div class="loadingio-spinner-double-ring-zjbfq8k35x relative">
      <div class="ldio-aanj0da69dw">
        <div></div>
        <div></div>
        <div><div></div></div>
        <div><div></div></div>
      </div>
      <img
        src="@/images/Logo.png"
        class="absolute top-[68px] left-[68px] w-36 h-36"
      />
    </div>
    <!-- progress bar -->
    <div
      class="mt-4 w-full bg-gray-500 rounded-full relative overflow-hidden"
      v-if="loadings.opacity === 1"
    >
      <div class="absolute text-xs font-medium left-[calc(50%-8px)] text-white">
        {{ loadings.progress }}%
      </div>
      <div
        class="bar bg-primary2 p-0.5 leading-none rounded-full transition-all h-4"
        :style="`width: ${loadings.progress}%`"
      ></div>
    </div>
  </VueLoading>
  <router-view />
</template>

<script>
// import { RouterLink, RouterView } from 'vue-router'
import { mapState } from "pinia";
import loadingStore from "@/stores/loadingStore.js";

export default {
  computed: {
    ...mapState(loadingStore, ["loadings"]),
  },
};
</script>

<style lang="scss">
@import "./assets/all.scss";
</style>

<!-- loading css -->
<style type="text/css">
@keyframes ldio-aanj0da69dw {
  0% {
    transform: rotate(0);
  }
  100% {
    transform: rotate(360deg);
  }
}
.ldio-aanj0da69dw div {
  box-sizing: border-box !important;
}
.ldio-aanj0da69dw > div {
  position: absolute;
  width: 260.4px;
  height: 260.4px;
  top: 9.799999999999999px;
  left: 9.799999999999999px;
  border-radius: 50%;
  border: 14px solid #000;
  border-color: #553c99 transparent #553c99 transparent;
  animation: ldio-aanj0da69dw 1s linear infinite;
}

.ldio-aanj0da69dw > div:nth-child(2),
.ldio-aanj0da69dw > div:nth-child(4) {
  width: 226.79999999999998px;
  height: 226.79999999999998px;
  top: 26.599999999999998px;
  left: 26.599999999999998px;
  animation: ldio-aanj0da69dw 1s linear infinite reverse;
}
.ldio-aanj0da69dw > div:nth-child(2) {
  border-color: transparent #7fcce3 transparent #7fcce3;
}
.ldio-aanj0da69dw > div:nth-child(3) {
  border-color: transparent;
}
.ldio-aanj0da69dw > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-aanj0da69dw > div:nth-child(3) div:before,
.ldio-aanj0da69dw > div:nth-child(3) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 14px;
  height: 14px;
  top: -14px;
  left: 109.19999999999999px;
  background: #553c99;
  border-radius: 50%;
  box-shadow: 0 246.39999999999998px 0 0 #553c99;
}
.ldio-aanj0da69dw > div:nth-child(3) div:after {
  left: -14px;
  top: 109.19999999999999px;
  box-shadow: 246.39999999999998px 0 0 0 #553c99;
}

.ldio-aanj0da69dw > div:nth-child(4) {
  border-color: transparent;
}
.ldio-aanj0da69dw > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-aanj0da69dw > div:nth-child(4) div:before,
.ldio-aanj0da69dw > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 14px;
  height: 14px;
  top: -14px;
  left: 92.39999999999999px;
  background: #7fcce3;
  border-radius: 50%;
  box-shadow: 0 212.79999999999998px 0 0 #7fcce3;
}
.ldio-aanj0da69dw > div:nth-child(4) div:after {
  left: -14px;
  top: 92.39999999999999px;
  box-shadow: 212.79999999999998px 0 0 0 #7fcce3;
}
.loadingio-spinner-double-ring-zjbfq8k35x {
  width: 280px;
  height: 280px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-aanj0da69dw {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-aanj0da69dw div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
